from pathlib import Path
p=Path('index.html')
s=p.read_text()
css='''
.routeExperience{padding:76px 0;background:linear-gradient(180deg,#0d1916 0%,#08120f 100%);border-top:1px solid #ffffff12;border-bottom:1px solid #ffffff12}.rxHead{display:grid;grid-template-columns:1.15fr .85fr;gap:32px;align-items:end;margin-bottom:28px}.rxHead h2{font-size:clamp(38px,5.5vw,64px);line-height:.96;letter-spacing:-3px;margin:8px 0 0}.rxHead p{color:#aebdb6;line-height:1.7;margin:0}.rxGrid{display:grid;grid-template-columns:1.2fr .8fr;gap:16px}.rxStory{background:linear-gradient(135deg,#14271f,#0d1916);border:1px solid #294238;border-radius:26px;padding:24px;overflow:hidden;position:relative}.rxStory:after{content:'';position:absolute;right:-60px;top:-60px;width:220px;height:220px;border-radius:50%;background:#b9ff3810}.rxKicker{font-size:10px;font-weight:900;letter-spacing:2px;color:var(--green)}.rxStory h3{font-size:30px;letter-spacing:-1.3px;margin:10px 0 10px}.rxStory p{color:#c2cec8;line-height:1.7}.rxJourney{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:20px}.rxStop{background:#ffffff08;border:1px solid #ffffff12;border-radius:14px;padding:12px;min-height:96px}.rxStop span{font-size:18px}.rxStop b{display:block;margin-top:8px;font-size:12px}.rxStop small{display:block;color:#8fa198;margin-top:3px;line-height:1.35}.rxMetrics{display:grid;grid-template-columns:1fr 1fr;gap:10px}.rxMetric{background:#f2f6f3;color:#142118;border-radius:18px;padding:16px}.rxMetric small{font-size:9px;font-weight:900;letter-spacing:1px;color:#708078}.rxMetric strong{display:block;font-size:28px;margin-top:6px}.rxMetric p{margin:4px 0 0;color:#68776f;font-size:11px;line-height:1.4}.rxAdvice{grid-column:1/-1;background:#b9ff38;color:#132007;border-radius:18px;padding:16px}.rxAdvice small{font-size:9px;font-weight:950;letter-spacing:1.2px}.rxAdvice strong{display:block;font-size:20px;margin-top:5px}.rxAdvice p{color:#294215;margin:5px 0 0;font-size:12px;line-height:1.5}.rxConfidence{margin-top:12px;color:#7f9188;font-size:10px;line-height:1.5}.rxRibbon{height:7px;background:#1d3129;border-radius:99px;overflow:hidden;margin-top:18px}.rxRibbon i{display:block;height:100%;width:76%;background:linear-gradient(90deg,#b9ff38,#d6b35d)}
@media(max-width:900px){.rxHead,.rxGrid{grid-template-columns:1fr}.rxJourney{grid-template-columns:1fr 1fr}}@media(max-width:560px){.rxJourney,.rxMetrics{grid-template-columns:1fr}.rxStory h3{font-size:25px}}
'''
html='''
<section class="routeExperience" id="route-experience"><div class="wrap"><div class="rxHead"><div><div class="eyebrow">NEAR ROUTE EXPERIENCE</div><h2>The drive is part of the trip.</h2></div><p>Costa Rica can change character fast — cool mountain roads, rainforest, open valleys and coastal views can all belong to the same journey. NEAR interprets the route so your car fits both the road and the experience.</p></div><div class="rxGrid"><article class="rxStory"><div class="rxKicker">SCENIC ROUTE STORY · ESTIMATED</div><h3 id="rxTitle">From highland curves to tropical coast.</h3><p id="rxStory">Your route may move through changing elevation and landscapes before opening toward warmer lowlands and the Pacific. NEAR treats those transitions as part of the vehicle recommendation, not just the destination.</p><div class="rxJourney"><div class="rxStop"><span>⛰️</span><b>Highlands</b><small id="rxHigh">Curves, elevation and cooler air</small></div><div class="rxStop"><span>🌿</span><b>Green corridor</b><small id="rxGreen">Rainforest, valleys and changing weather</small></div><div class="rxStop"><span>🛞</span><b>Adventure leg</b><small id="rxRoad">Possible gravel, steep or narrow sections</small></div><div class="rxStop"><span>🌊</span><b>Coast</b><small id="rxCoast">Warmer air, ocean views and beach access</small></div></div><div class="rxRibbon"><i id="rxRibbon"></i></div><div class="rxConfidence" id="rxConfidence">NEAR Scenic Intelligence uses destination and route-profile signals. Until live road/elevation feeds are connected, scenic and surface details are presented as informed estimates, not live road conditions.</div></article><aside class="rxMetrics"><div class="rxMetric"><small>ADVENTURE PROFILE</small><strong id="rxAdventure">High</strong><p id="rxAdventureText">More changes in terrain, elevation and road character.</p></div><div class="rxMetric"><small>SCENIC POTENTIAL</small><strong id="rxScenic">Excellent</strong><p id="rxScenicText">Strong potential for varied mountain-to-coast scenery.</p></div><div class="rxMetric"><small>VEHICLE CONFIDENCE</small><strong id="rxVehicle">4x4</strong><p id="rxVehicleText">Extra clearance and traction improve confidence on mixed routes.</p></div><div class="rxMetric"><small>DRIVE CHARACTER</small><strong id="rxCharacter">Dynamic</strong><p id="rxCharacterText">Expect the route to feel like part of the Costa Rica experience.</p></div><div class="rxAdvice"><small>NEAR SMART VEHICLE ADVICE</small><strong id="rxAdvice">Choose confidence, not just the lowest price.</strong><p id="rxAdviceText">A small upgrade can be worthwhile when the route changes quickly between pavement, steep grades and rougher access roads.</p></div></aside></div></div></section>
'''
js='''
function updateRouteExperience(){
 const d=normalize((typeof r2!=='undefined'&&r2.value)||(typeof dropoff!=='undefined'&&dropoff.value)||'');
 const mode=routeMode||'mixed';
 const coastal=/jaco|uvita|dominical|manuel antonio|quepos|tamarindo|nosara|santa teresa|montezuma|pavones|drake|coco|papagayo/.test(d);
 const mountain=/monteverde|la fortuna|arenal|san gerardo|cerro|turrialba|monte|mountain/.test(d);
 const remote=mode==='remote';
 const cfg= remote ? {
  title:'Wild access, big scenery, the right vehicle matters.',story:'This is the kind of Costa Rica drive where the journey can feel genuinely adventurous: longer remote stretches, rougher access, sudden weather changes and dramatic landscape transitions. NEAR favors capability and clearance over shaving a few dollars from the quote.',adv:'Very high',scenic:'Exceptional',veh:'4x4',char:'Expedition',road:'Rougher or remote access can be part of the final leg',advice:'Prioritize capability and recovery margin.',adviceText:'For a remote profile, NEAR would rather place you in a capable 4x4 with clearance than optimize purely for the cheapest daily rate.',w:'94%'} : mode==='mountain' ? {
  title:coastal?'Mountain curves now. Ocean air soon.':'Elevation, curves and a more rewarding drive.',story:coastal?'One of Costa Rica’s signatures is how quickly the route can transform. You can leave a cooler, elevated section, cross lush valleys and descend toward tropical coastline in the same drive. That change in terrain is exactly why NEAR evaluates the car as part of the route.':'Mountain driving can combine elevation, tight curves, rain, scenic overlooks and changing road surfaces. NEAR gives Route Fit more importance here because comfort, braking confidence and clearance matter more than on a flat city transfer.',adv:'High',scenic:'Excellent',veh:'4x4 / AWD',char:'Scenic',road:'Curves, grades and possible rougher connectors',advice:'Choose stability and clearance for the whole journey.',adviceText:'An AWD or 4x4 SUV can add confidence when pavement quality, gradients or weather change during the route.',w:'86%'} : mode==='city' ? {
  title:'Easy driving, with Costa Rica still outside the window.',story:'This profile is predominantly straightforward. NEAR keeps the recommendation efficient and comfortable, while still recognizing that even an easy Costa Rica route can quickly open into green hills, palms, rivers and coastal horizons.',adv:'Low',scenic:'Good',veh:'2WD',char:'Relaxed',road:'Mostly straightforward paved driving',advice:'Do not pay for capability you are unlikely to use.',adviceText:'A comfortable automatic 2WD can be the smarter value when the route is mainly paved and accessible.',w:'42%'} : {
  title:coastal?'A mixed-road journey with a tropical finish.':'A little of everything — exactly what Costa Rica does well.',story:coastal?'Expect a balanced drive that may combine highways, local roads, green interior scenery and a final transition toward the coast. NEAR looks for a vehicle that stays comfortable on pavement without feeling out of place when the route becomes narrower or rougher.':'This route profile mixes different road environments. It is not an expedition, but it benefits from a vehicle that can handle changing pavement quality, local roads and occasional rougher sections without sacrificing comfort.',adv:'Moderate',scenic:'Very good',veh:'SUV preferred',char:'Varied',road:'Paved roads with possible mixed-surface sections',advice:'Balance comfort, price and extra road confidence.',adviceText:'A compact SUV is often the sweet spot for a mixed Costa Rica itinerary: comfortable, easy to drive and better prepared for changing road character.',w:'68%'};
 rxTitle.textContent=cfg.title;rxStory.textContent=cfg.story;rxAdventure.textContent=cfg.adv;rxScenic.textContent=cfg.scenic;rxVehicle.textContent=cfg.veh;rxCharacter.textContent=cfg.char;rxRoad.textContent=cfg.road;rxAdvice.textContent=cfg.advice;rxAdviceText.textContent=cfg.adviceText;rxRibbon.style.width=cfg.w;
 rxHigh.textContent=mountain?'Elevation, curves and cooler mountain air':'Possible inland hills and changing elevation';
 rxCoast.textContent=coastal?'A clear transition toward ocean and beach country':'Coastal scenery may be nearby depending on itinerary';
}
'''
if '.routeExperience{' not in s:
    s=s.replace('.results{display:none',css+'\n.results{display:none')
if 'id="route-experience"' not in s:
    s=s.replace('<section class="results"',html+'\n<section class="results"')
if 'function updateRouteExperience()' not in s:
    s=s.replace('function priceScore(c)',js+'\nfunction priceScore(c)')
    s=s.replace('function applyRoute(mode,note){routeMode=mode;',"function applyRoute(mode,note){routeMode=mode;setTimeout(()=>{try{updateRouteExperience()}catch(e){}},0);")
p.write_text(s)
# route-experience-v2
