from pathlib import Path
p=Path('index.html')
s=p.read_text()
css=r'''
.liveRoute{padding:78px 0;background:#07110f}.lrHead{display:grid;grid-template-columns:1.05fr .95fr;gap:30px;align-items:end;margin-bottom:24px}.lrHead h2{font-size:clamp(38px,5.5vw,64px);line-height:.96;letter-spacing:-3px;margin:8px 0 0}.lrHead p{color:#9fb0a8;line-height:1.7;margin:0}.lrGrid{display:grid;grid-template-columns:1.4fr .6fr;gap:16px}.mapShell{background:#0d1916;border:1px solid #22332d;border-radius:24px;overflow:hidden;position:relative}.mapTop{padding:15px 16px;display:flex;justify-content:space-between;gap:12px;align-items:center;border-bottom:1px solid #22332d}.mapTop b{font-size:12px}.mapTop small{color:#84978e}.livePill{font-size:9px;font-weight:950;letter-spacing:1px;border-radius:99px;background:#173527;color:#b9ff38;padding:7px 9px}.livePill.fallback{background:#302817;color:#f0cd78}.nearMap{height:470px;background:#dfe9e4}.mapNotice{position:absolute;left:16px;bottom:16px;z-index:500;background:#08130fee;color:#e7f0eb;border:1px solid #ffffff20;border-radius:12px;padding:10px 12px;font-size:10px;max-width:280px;line-height:1.45}.signalPanel{display:grid;gap:12px}.signalBox{background:#0d1916;border:1px solid #22332d;border-radius:20px;padding:16px}.signalBox h3{margin:0 0 5px;font-size:18px}.signalBox p{margin:0;color:#8fa198;font-size:12px;line-height:1.5}.signalList{display:grid;gap:8px;margin-top:12px;max-height:265px;overflow:auto}.signalItem{background:#13231d;border:1px solid #263b32;border-radius:13px;padding:10px}.signalItem b{display:block;font-size:11px}.signalItem small{color:#8da097;line-height:1.4}.signalItem img{width:100%;height:110px;object-fit:cover;border-radius:9px;margin-top:8px}.addRoute{background:#eef3ef;color:#132019;border-radius:20px;padding:16px}.addRoute h3{margin:0 0 4px}.addRoute p{color:#66776e;font-size:11px;line-height:1.45}.addRoute select,.addRoute textarea,.addRoute input[type=file]{width:100%;margin-top:9px;border:1px solid #cbd6d0;border-radius:11px;background:#fff;padding:10px}.addRoute textarea{min-height:82px;resize:vertical}.addSignalBtn{width:100%;border:0;border-radius:12px;background:#b9ff38;color:#142007;font-weight:950;padding:13px;margin-top:10px}.addSignalBtn:disabled{opacity:.5}.sigStatus{font-size:10px;margin-top:8px;color:#5c6c64;line-height:1.45}.sigPreview{display:none;width:100%;height:120px;object-fit:cover;border-radius:10px;margin-top:9px}.sigCats{display:flex;flex-wrap:wrap;gap:6px;margin-top:11px}.sigCat{font-size:9px;border:1px solid #2c4339;border-radius:99px;padding:6px 8px;color:#b9c8c1}.lrLegend{padding:12px 16px;border-top:1px solid #22332d;display:flex;gap:12px;flex-wrap:wrap;font-size:9px;color:#8fa198}.lrLegend b{color:#dfe8e3}.leaflet-popup-content-wrapper,.leaflet-popup-tip{background:#0d1916;color:#fff}.leaflet-popup-content{margin:10px 12px;font-size:11px}.leaflet-control-attribution{font-size:8px!important}
@media(max-width:900px){.lrHead,.lrGrid{grid-template-columns:1fr}.nearMap{height:390px}}@media(max-width:560px){.nearMap{height:330px}.lrHead h2{letter-spacing:-2px}}
'''
html=r'''
<section class="liveRoute" id="live-route"><div class="wrap"><div class="lrHead"><div><div class="eyebrow">NEAR LIVE ROUTE + DRIVER SIGNALS</div><h2>A route that gets smarter every time it is driven.</h2></div><p>Follow the real trip geometry when live routing is available, see approved signals left by recent NEAR drivers, and add a photo or useful update from the road. Community reports are dated and moderated before they become public.</p></div><div class="lrGrid"><div class="mapShell"><div class="mapTop"><div><b id="lrRouteName">Current NEAR route</b><br><small id="lrRouteMeta">Preparing route layer…</small></div><span class="livePill fallback" id="lrLivePill">ROUTE INTELLIGENCE</span></div><div id="nearLiveMap" class="nearMap"></div><div class="mapNotice" id="lrMapNotice">Live geometry appears when NEAR receives route coordinates. Driver Signals can still be added from your current GPS position.</div><div class="lrLegend"><span><b>●</b> Route</span><span>📸 Scenic / viewpoint</span><span>🛞 Road condition</span><span>⚠ Caution</span><span>⛽ Fuel</span><span>☕ Food / coffee</span></div></div><aside class="signalPanel"><div class="signalBox"><h3>Driver Signals</h3><p>Only approved, recent contributions appear publicly.</p><div class="sigCats"><span class="sigCat">SCENIC</span><span class="sigCat">ROAD</span><span class="sigCat">BEACH</span><span class="sigCat">WILDLIFE</span><span class="sigCat">FUEL</span><span class="sigCat">CAUTION</span></div><div class="signalList" id="driverSignals"><div class="signalItem"><small>No approved signals for this route yet. Be the first NEAR driver to contribute.</small></div></div></div><div class="addRoute"><h3>Add to this route</h3><p>Your current GPS position will be attached to the contribution. Photos are limited to 5 MB and new reports remain pending until reviewed.</p><select id="sigCategory"><option value="SCENIC_STOP">Scenic stop</option><option value="ROAD_CONDITION">Road condition</option><option value="FOOD_COFFEE">Food / coffee</option><option value="BEACH">Beach</option><option value="VIEWPOINT">Viewpoint</option><option value="WILDLIFE">Wildlife</option><option value="FUEL">Fuel</option><option value="CAUTION">Caution</option></select><textarea id="sigNote" maxlength="500" placeholder="What should the next driver know?"></textarea><input id="sigPhoto" type="file" accept="image/jpeg,image/png,image/webp"><img id="sigPreview" class="sigPreview" alt="Route signal preview"><button class="addSignalBtn" id="sigSubmit" onclick="submitRouteSignal()">ADD FROM MY GPS →</button><div class="sigStatus" id="sigStatus">GPS is requested only when you submit.</div></div></aside></div></div></section>
'''
js=r'''
const NEAR_SUPABASE_URL='https://oxatqxaddtkjnyfrvmot.supabase.co';
const NEAR_SUPABASE_KEY='sb_publishable_4cidR7RuGWYAOOrLsLA82A_n_Gkr1WG';
let nearMap=null,nearRouteLayer=null,nearSignalLayer=null,lastRouteData=null;
const sigIcon={SCENIC_STOP:'📸',ROAD_CONDITION:'🛞',FOOD_COFFEE:'☕',BEACH:'🌊',VIEWPOINT:'👁',WILDLIFE:'🦥',FUEL:'⛽',CAUTION:'⚠'};
function routeKey(){return (normalize((pickup?.value||'')+'-'+(dropoff?.value||''))).replace(/[^a-z0-9-]+/g,'-').replace(/-+/g,'-').slice(0,180)}
function initNearLiveMap(){if(nearMap||typeof L==='undefined')return;nearMap=L.map('nearLiveMap',{zoomControl:true}).setView([9.7489,-83.7534],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(nearMap);nearSignalLayer=L.layerGroup().addTo(nearMap)}
function markerIcon(cat){return L.divIcon({className:'',html:`<div style="width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#0d1916;border:2px solid #b9ff38;font-size:15px;box-shadow:0 4px 12px #0006">${sigIcon[cat]||'●'}</div>`,iconSize:[30,30],iconAnchor:[15,15]})}
async function loadDriverSignals(){if(!nearSignalLayer)return;nearSignalLayer.clearLayers();const key=routeKey();if(!key)return;try{const u=`${NEAR_SUPABASE_URL}/rest/v1/near_drive_route_signals?route_key=eq.${encodeURIComponent(key)}&approved=eq.true&select=id,created_at,category,note,latitude,longitude,photo_url&order=created_at.desc&limit=30`;const r=await fetch(u,{headers:{apikey:NEAR_SUPABASE_KEY,Authorization:`Bearer ${NEAR_SUPABASE_KEY}`}});const data=await r.json();if(!r.ok)throw new Error(data?.message||'Unable to load signals');driverSignals.innerHTML=data.length?data.map(x=>`<div class="signalItem"><b>${sigIcon[x.category]||'●'} ${x.category.replaceAll('_',' ')}</b><small>${escapeSignal(x.note||'Recent NEAR driver signal')} · ${new Date(x.created_at).toLocaleDateString()}</small>${x.photo_url?`<img src="${x.photo_url}" alt="Driver route signal">`:''}</div>`).join(''):'<div class="signalItem"><small>No approved signals for this route yet. Be the first NEAR driver to contribute.</small></div>';data.forEach(x=>{const m=L.marker([x.latitude,x.longitude],{icon:markerIcon(x.category)}).addTo(nearSignalLayer);m.bindPopup(`<b>${sigIcon[x.category]||'●'} ${x.category.replaceAll('_',' ')}</b><br>${escapeSignal(x.note||'NEAR driver signal')}${x.photo_url?`<br><img src="${x.photo_url}" style="width:180px;margin-top:7px;border-radius:8px">`:''}`)})}catch(e){driverSignals.innerHTML='<div class="signalItem"><small>Driver Signals are temporarily unavailable.</small></div>'}}
function escapeSignal(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderLiveGeometry(data){initNearLiveMap();lastRouteData=data||null;lrRouteName.textContent=(pickup?.value||'Pickup')+' → '+(dropoff?.value||'Destination');const coords=data?.geometry?.coordinates;if(Array.isArray(coords)&&coords.length>1){if(nearRouteLayer)nearMap.removeLayer(nearRouteLayer);const latlngs=coords.map(c=>[c[1],c[0]]);nearRouteLayer=L.polyline(latlngs,{weight:5,opacity:.88}).addTo(nearMap);nearMap.fitBounds(nearRouteLayer.getBounds(),{padding:[28,28]});lrRouteMeta.textContent=(data.distanceKm?data.distanceKm+' km · ':'')+(data.level||'Route analyzed')+' · '+(data.source||'NEAR route data');lrLivePill.textContent=data.live?'LIVE ROUTE':'ROUTE PROFILE';lrLivePill.classList.toggle('fallback',!data.live);lrMapNotice.textContent='Route geometry is based on the current route response. Driver Signals are separate community observations and are always dated.'}else{lrRouteMeta.textContent=(data?.level||'Route profile')+' · '+(data?.source||'NEAR destination intelligence');lrLivePill.textContent='ROUTE PROFILE';lrLivePill.classList.add('fallback');lrMapNotice.textContent='Live route geometry is not available for this search yet. Driver Signals can still be added from your current GPS position.'}loadDriverSignals()}
function nearGps(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS is not supported on this device.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),()=>reject(new Error('Location permission is required to add a Driver Signal.')),{enableHighAccuracy:true,timeout:12000,maximumAge:30000})})}
async function uploadSignalPhoto(file){if(!file)return null;if(file.size>5*1024*1024)throw new Error('Photo must be 5 MB or smaller.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Use JPG, PNG or WebP.');const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const name=`${Date.now()}-${Math.random().toString(36).slice(2,9)}.${ext}`;const path=`public/${routeKey()}/${name}`;const r=await fetch(`${NEAR_SUPABASE_URL}/storage/v1/object/near-drive-route-signals/${path}`,{method:'POST',headers:{apikey:NEAR_SUPABASE_KEY,Authorization:`Bearer ${NEAR_SUPABASE_KEY}`,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j?.message||'Photo upload failed.')}return `${NEAR_SUPABASE_URL}/storage/v1/object/public/near-drive-route-signals/${path}`}
async function submitRouteSignal(){sigSubmit.disabled=true;sigStatus.textContent='Getting your GPS position…';try{const pos=await nearGps();sigStatus.textContent='Preparing contribution…';const photo=await uploadSignalPhoto(sigPhoto.files?.[0]);const body={route_key:routeKey(),reservation_code:null,category:sigCategory.value,note:sigNote.value.trim()||null,latitude:pos.lat,longitude:pos.lng,photo_url:photo,approved:false};const r=await fetch(`${NEAR_SUPABASE_URL}/rest/v1/near_drive_route_signals`,{method:'POST',headers:{apikey:NEAR_SUPABASE_KEY,Authorization:`Bearer ${NEAR_SUPABASE_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(body)});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j?.message||'Unable to save Driver Signal.')}initNearLiveMap();L.marker([pos.lat,pos.lng],{icon:markerIcon(sigCategory.value)}).addTo(nearMap).bindPopup('<b>Your new signal</b><br>Pending moderation.').openPopup();nearMap.setView([pos.lat,pos.lng],14);sigNote.value='';sigPhoto.value='';sigPreview.style.display='none';sigStatus.textContent='Submitted successfully · pending moderation before it becomes public.'}catch(e){sigStatus.textContent=e.message||'Unable to add this signal.'}finally{sigSubmit.disabled=false}}
document.addEventListener('DOMContentLoaded',()=>{initNearLiveMap();loadDriverSignals();if(sigPhoto)sigPhoto.addEventListener('change',()=>{const f=sigPhoto.files?.[0];if(!f){sigPreview.style.display='none';return}sigPreview.src=URL.createObjectURL(f);sigPreview.style.display='block'})});
'''
# add leaflet assets
if 'leaflet@1.9.4' not in s:
    s=s.replace('</head>','<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIINfQ3ynHt+6XjMZRF6u9ZtTga5hQp7QfM=" crossorigin="">\n</head>')
    s=s.replace('<script>','<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>\n<script>',1)
if '.liveRoute{' not in s:
    s=s.replace('.results{display:none',css+'\n.results{display:none')
if 'id="live-route"' not in s:
    s=s.replace('<section class="results"',html+'\n<section class="results"')
if 'function submitRouteSignal()' not in s:
    s=s.replace('function priceScore(c)',js+'\nfunction priceScore(c)')
# wire route response into map while preserving existing behavior
needle="if(!resp.ok)return; const live=await resp.json();"
if needle in s and 'renderLiveGeometry(live)' not in s:
    s=s.replace(needle,needle+' renderLiveGeometry(live);')
# fallback profile should still refresh map/signals
needle2='const fallback=inferRoute(origin,destination);applyRoute(fallback.mode,fallback.note);'
if needle2 in s and 'renderLiveGeometry(fallback)' not in s:
    s=s.replace(needle2,needle2+'renderLiveGeometry({...fallback,live:false,source:\'NEAR destination intelligence\'});')
p.write_text(s)

# expose geometry from route API when live
rp=Path('api/route.js')
r=rp.read_text()
old="return res.status(200).json({\n      live:true,source:'NEAR AI + openrouteservice',confidence:92,origin,destination,distanceKm,score,level,need4x4,"
new="return res.status(200).json({\n      live:true,source:'NEAR AI + openrouteservice',confidence:92,origin,destination,distanceKm,score,level,need4x4,geometry:f?.geometry||null,"
if old in r and 'geometry:f?.geometry||null' not in r:
    r=r.replace(old,new)
rp.write_text(r)
