from pathlib import Path
p=Path('admin.html')
s=p.read_text()
s=s.replace(".stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:20px}",".stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:20px}")
s=s.replace(".save{background:#0d1916;color:#fff}",".save{background:#0d1916;color:#fff}.next{background:#eaf7c8;border:1px solid #c6df86;border-radius:14px;padding:12px;margin-bottom:10px}.next small{display:block;color:#65734f;font-weight:900;letter-spacing:1px}.next b{display:block;margin-top:4px;font-size:15px}.profit{margin-top:12px;background:#eef6ef;border-radius:12px;padding:11px}.profit b{color:#416600}.voucher{background:#b9ff38;color:#142007}.voucher:disabled{opacity:.45;cursor:not-allowed}")
s=s.replace("<div class=\"stat\"><small>Gross sales</small><b id=\"sGross\">$0</b></div>","<div class=\"stat\"><small>Gross sales</small><b id=\"sGross\">$0</b></div><div class=\"stat\"><small>Gross profit</small><b id=\"sProfit\">$0</b></div>")
old="function render(){sPending.textContent=all.filter(x=>x.status==='SUPPLIER_PENDING').length;sConfirmed.textContent=all.filter(x=>x.status==='CONFIRMED_WITH_SUPPLIER').length;sVoucher.textContent=all.filter(x=>x.status==='VOUCHER_SENT').length;sGross.textContent='$'+all.filter(x=>x.payment_status==='PAID_TO_NEAR'&&x.status!=='CANCELLED').reduce((a,x)=>a+Number(x.total||0),0).toLocaleString(undefined,{maximumFractionDigits:0});const list=filter==='ALL'?all:all.filter(x=>x.status===filter);cards.innerHTML=list.length?list.map(card).join(''):'<div class=\"empty\">No reservations in this status.</div>'}"
new="function nextAction(r){if(r.status==='CANCELLED')return 'No action · cancelled';if(r.status==='COMPLETED')return 'Closed · completed';if(!r.supplier_name)return 'Book with rental supplier';if(!r.supplier_confirmation_number)return 'Enter supplier confirmation number';if(!r.supplier_paid)return 'Pay rental supplier';if(r.status==='SUPPLIER_PENDING')return 'Mark confirmed with supplier';if(r.status==='CONFIRMED_WITH_SUPPLIER')return 'Send final voucher to customer';if(r.status==='VOUCHER_SENT')return 'Monitor pickup';if(r.status==='VEHICLE_PICKED_UP')return 'Mark completed after rental';return 'Review reservation'}\nfunction render(){sPending.textContent=all.filter(x=>x.status==='SUPPLIER_PENDING').length;sConfirmed.textContent=all.filter(x=>x.status==='CONFIRMED_WITH_SUPPLIER').length;sVoucher.textContent=all.filter(x=>x.status==='VOUCHER_SENT').length;const active=all.filter(x=>x.payment_status==='PAID_TO_NEAR'&&x.status!=='CANCELLED');sGross.textContent='$'+active.reduce((a,x)=>a+Number(x.total||0),0).toLocaleString(undefined,{maximumFractionDigits:0});sProfit.textContent='$'+active.reduce((a,x)=>a+(x.supplier_cost==null?0:Number(x.total||0)-Number(x.supplier_cost||0)),0).toLocaleString(undefined,{maximumFractionDigits:0});const list=filter==='ALL'?all:all.filter(x=>x.status===filter);cards.innerHTML=list.length?list.map(card).join(''):'<div class=\"empty\">No reservations in this status.</div>'}"
if old not in s: raise SystemExit('render pattern not found')
s=s.replace(old,new)
start=s.index('function card(r){')
end=s.index('\nasync function save',start)
newcard='''function card(r){const profit=r.supplier_cost==null?null:Number(r.total||0)-Number(r.supplier_cost||0),margin=profit==null||!Number(r.total)?null:Math.round(profit/Number(r.total)*100);return `<article class="card" data-id="${r.id}"><div><div class="next"><small>NEXT ACTION</small><b>${esc(nextAction(r))}</b></div><div class="code">${esc(r.code)}</div><h2>${esc(r.vehicle)}</h2><span class="badge">${esc(r.status.replaceAll('_',' '))}</span><div class="meta" style="margin-top:10px"><b>${esc(r.customer_first_name)} ${esc(r.customer_last_name)}</b><br>${esc(r.customer_email)}<br>${esc(r.customer_phone)}<br><br>${esc(r.pickup||'—')} → ${esc(r.destination||'—')}<br>${esc(r.start_date||'—')} → ${esc(r.end_date||'—')}</div></div><div><div class="money">$${Number(r.total||0).toFixed(2)}</div><div class="meta">Customer paid to NEAR<br>Rental balance at desk: <b>$0</b><br>Security deposit: <b>$${Number(r.deposit||0).toFixed(2)}</b><br>Supplier cost: <b>${r.supplier_cost==null?'—':'$'+Number(r.supplier_cost).toFixed(2)}</b></div><div class="profit"><small>GROSS PROFIT</small><br><b>${profit==null?'Enter supplier cost':'$'+profit.toFixed(2)+(margin==null?'':' · '+margin+'% margin')}</b></div><div class="meta" style="margin-top:12px">Flight: ${esc(r.flight_number||'—')}<br>Delivery: ${esc(r.delivery_address||'—')}<br>Extras: ${esc((r.extras||[]).join(', ')||'None')}</div></div><div class="adminFields"><select data-f="status">${['SUPPLIER_PENDING','CONFIRMED_WITH_SUPPLIER','VOUCHER_SENT','VEHICLE_PICKED_UP','COMPLETED','CANCELLED'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select><input data-f="supplier_name" placeholder="Rental company" value="${esc(r.supplier_name||'')}"><input data-f="supplier_confirmation_number" placeholder="Supplier confirmation #" value="${esc(r.supplier_confirmation_number||'')}"><input data-f="supplier_cost" type="number" step="0.01" min="0" placeholder="Supplier cost" value="${r.supplier_cost??''}"><label class="meta"><input data-f="supplier_paid" type="checkbox" ${r.supplier_paid?'checked':''}> Supplier paid by NEAR</label><textarea data-f="admin_notes" placeholder="Internal notes">${esc(r.admin_notes||'')}</textarea><button class="btn save" onclick="save(${r.id},this)">SAVE RESERVATION</button><button class="btn voucher" onclick="sendVoucher(${r.id},this)" ${(!r.supplier_name||!r.supplier_confirmation_number||r.status==='CANCELLED')?'disabled':''}>SEND FINAL VOUCHER →</button><div class="meta" data-msg></div></div></article>`}'''
s=s[:start]+newcard+s[end:]
insert="""\nasync function sendVoucher(id,btn){const el=btn.closest('.card'),msg=el.querySelector('[data-msg]'),{data:{session}}=await db.auth.getSession();if(!session){msg.textContent='Session expired. Sign in again.';return}btn.disabled=true;msg.textContent='Sending voucher…';try{const r=await fetch('/api/voucher',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({id})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to send voucher');msg.textContent='Voucher sent to customer';msg.style.color='#527400';await load()}catch(e){msg.textContent=e.message;msg.style.color='#a52a2a';btn.disabled=false}}\n"""
pos=s.index('\nfilters.onclick=')
s=s[:pos]+insert+s[pos:]
p.write_text(s)
