from pathlib import Path
p=Path('index.html')
s=p.read_text()
css='''.checkoutnote{margin:14px 0 0;padding:12px 14px;border-radius:12px;background:#eef7ef;color:#395148;font-size:12px;line-height:1.5}.checkoutnote b{color:#244d3b}.terms{display:flex;gap:10px;align-items:flex-start;margin-top:14px;background:#fff;border:1px solid #d4ddd8;border-radius:12px;padding:12px;color:#415149;font-size:12px}.terms input{margin-top:3px;accent-color:#5f8f00}.fieldError{border-color:#d9544d!important;box-shadow:0 0 0 2px #d9544d22}.errorbox{display:none;margin-top:12px;padding:11px 13px;border-radius:11px;background:#ffe7e4;color:#7a211b;font-size:12px;font-weight:750}.errorbox.show{display:block}.reservation{max-width:720px;margin:auto}.rescard{background:#fff;border:1px solid #dce5df;border-radius:18px;padding:18px;text-align:left;margin:20px auto}.resrow{display:flex;justify-content:space-between;gap:20px;padding:9px 0;border-bottom:1px solid #edf1ef;font-size:13px}.resrow:last-child{border:0}.rescode{font-size:30px;font-weight:950;color:#527400;letter-spacing:-1px}.payready{margin-top:14px;padding:12px;border-radius:12px;background:#f3f6f4;color:#5d6b65;font-size:11px;line-height:1.5}\n'''
if '.checkoutnote{' not in s:s=s.replace('@media(max-width:900px)',css+'@media(max-width:900px)',1)
repls={
'<input placeholder="First name">':'<input id="coFirst" placeholder="First name *" autocomplete="given-name">',
'<input placeholder="Last name">':'<input id="coLast" placeholder="Last name *" autocomplete="family-name">',
'<input type="email" placeholder="Email">':'<input id="coEmail" type="email" placeholder="Email *" autocomplete="email">',
'<input type="tel" placeholder="Phone / WhatsApp">':'<input id="coPhone" type="tel" placeholder="Phone / WhatsApp *" autocomplete="tel">',
'<select><option>Country of residence</option>':'<select id="coCountry"><option value="">Country of residence *</option>',
'<input placeholder="Flight number (optional)">':'<input id="coFlight" placeholder="Flight number (optional)">',
'<input class="full" placeholder="Delivery address / hotel / villa (optional)">':'<input id="coDelivery" class="full" placeholder="Delivery address / hotel / villa (optional)">'}
for a,b in repls.items():s=s.replace(a,b)
target='<div class="confirmbox"><div><small>RESERVATION TOTAL</small>'
insert='<div class="checkoutnote"><b>Reservation step</b><br>Your selected vehicle, NEAR AI route analysis and chosen extras will be attached to this reservation.</div><label class="terms"><input id="coTerms" type="checkbox"><span>I agree to the rental conditions, cancellation policy and final price shown above.</span></label><div class="errorbox" id="checkoutError"></div><div class="confirmbox"><div><small>RESERVATION TOTAL</small>'
if 'id="coTerms"' not in s:s=s.replace(target,insert,1)
s=s.replace('onclick="completeDemo()">RESERVE VEHICLE →','onclick="completeCheckout()">CONFIRM RESERVATION →',1)
funcs=r'''function validateCheckout(){const fields=[coFirst,coLast,coEmail,coPhone,coCountry];fields.forEach(x=>x&&x.classList.remove('fieldError'));let bad=[];if(!coFirst.value.trim())bad.push(coFirst);if(!coLast.value.trim())bad.push(coLast);if(!/^\S+@\S+\.\S+$/.test(coEmail.value.trim()))bad.push(coEmail);if(coPhone.value.replace(/\D/g,'').length<7)bad.push(coPhone);if(!coCountry.value)bad.push(coCountry);bad.forEach(x=>x.classList.add('fieldError'));if(bad.length){checkoutError.textContent='Please complete your name, valid email, phone/WhatsApp and country of residence.';checkoutError.classList.add('show');return false}if(!coTerms.checked){checkoutError.textContent='Please accept the rental conditions and final price to continue.';checkoutError.classList.add('show');return false}checkoutError.classList.remove('show');return true}
function reservationCode(){const d=new Date(),n=String(Math.floor(Math.random()*9000)+1000);return 'ND-'+d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0')+'-'+n}
function selectedExtras(){return [...document.querySelectorAll('.extra:checked')].map(x=>x.closest('.option')?.querySelector('b')?.textContent||'Extra')}
function completeCheckout(){if(!validateCheckout())return;const code=reservationCode(),total=getTotal(),extras=selectedExtras();const reservation={code,createdAt:new Date().toISOString(),vehicle:selected.name,match:selected.match,total,deposit:selected.deposit,pickup:pickup.value,destination:dropoff.value,start:start.value,end:end.value,routeMode,driver:{first:coFirst.value.trim(),last:coLast.value.trim(),email:coEmail.value.trim(),phone:coPhone.value.trim(),country:coCountry.value,flight:coFlight.value.trim(),delivery:coDelivery.value.trim()},extras};try{localStorage.setItem('nearDriveLastReservation',JSON.stringify(reservation))}catch(e){}detail.innerHTML=`<div class="reservation" style="padding:50px 24px;text-align:center"><div style="font-size:54px">✓</div><div class="eyebrow" style="color:#527400">NEAR DRIVE · RESERVATION CREATED</div><h2>Your vehicle is selected.</h2><p style="color:#66766e">NEAR AI route analysis and your True Price selection are attached to this reservation.</p><div class="rescard"><div style="font-size:10px;color:#77867f;font-weight:900">RESERVATION NUMBER</div><div class="rescode">${code}</div><div class="resrow"><span>Vehicle</span><b>${selected.name}</b></div><div class="resrow"><span>NEAR Match</span><b>${selected.match}%</b></div><div class="resrow"><span>Route</span><b>${pickup.value} → ${dropoff.value}</b></div><div class="resrow"><span>Dates</span><b>${start.value} → ${end.value}</b></div><div class="resrow"><span>Extras</span><b>${extras.length?extras.join(', '):'None'}</b></div><div class="resrow"><span>True Price</span><b>$${total}</b></div><div class="resrow"><span>Deposit</span><b>$${selected.deposit}</b></div></div><div class="payready"><b>Payment integration ready:</b> this confirmation step is isolated so real payment authorization and supplier booking can be inserted here without changing the customer flow.</div><button class="continue" style="max-width:300px" onclick="closeDeal()">BACK TO NEAR DRIVE</button></div>`}
'''
if 'function validateCheckout()' not in s:s=s.replace('function completeDemo(){',funcs+'function completeDemo(){',1)
p.write_text(s)
